language: php
dist: bionic

php:
  - 7.4
  - 8.0
  - 8.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

notifications:
  slack: kumbiaphp:51JaKQTXASwf52D8b32OyWb9
#    irc: "irc.freenode.org#kumbiaphp"
#    email:
#    - xxxxx@gmail.com

services:
  - mysql
  - postgresql

install:
  - composer install

before_script:
  - "mysql -e 'DROP DATABASE IF EXISTS kumbia_test;'"
  - "mysql -e 'create database kumbia_test;'"
  - "psql -c 'DROP DATABASE IF EXISTS kumbia_test;' -U postgres"
  - "psql -c 'create database kumbia_test;' -U postgres"
                                            
script: 
  - phpunit --version
  - phpunit --configuration tests/phpunit.xml --coverage-text --colors --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
