language: php
dist: bionic

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

notifications:
  slack: kumbiaphp:51JaKQTXASwf52D8b32OyWb9
#    irc: "irc.freenode.org#kumbiaphp"
#    email:
#    - programador.manuel@gmail.com

services:
  - mysql
  - postgresql

env:
  - DB=mysql
  - DB=pgsql
#  - DB=sqlite

before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS kumbia_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c 'CREATE DATABASE kumbia_test;' -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c 'CREATE TABLE IF NOT EXISTS test ( 
                                                        id serial PRIMARY KEY, 
                                                        nombre  varchar(50) NOT NULL , 
                                                        email varchar(100) NOT NULL , 
                                                        activo smallint NULL DEFAULT 1 
                                                      );' 
                                                  -U postgres;
                                                fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'CREATE DATABASE IF NOT EXISTS kumbia_test;
                                                  CREATE TABLE IF NOT EXISTS kumbia_test.test ( 
                                                    id BIGINT(20) NOT NULL AUTO_INCREMENT, 
                                                    nombre  varchar(50) NOT NULL , 
                                                    email varchar(100) NOT NULL , 
                                                    activo smallint(1) NULL DEFAULT 1 , 
                                                    PRIMARY KEY (id) );'
                                                  ; fi
                                                
script: 
  - phpunit --configuration tests/phpunit.xml --coverage-text --colors --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
